---
host: 127.0.0.1
ip_route: 127.0.0.1
index: 0
logging:
  level: debug
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/filesystem_node.pid

max_fs_size: 100 # in MB
capacity: 20 # slots
allow_over_provisioning: false

base_dir: /var/vcap/services/filesystem/storage
