---
cloud_controller_uri: api.vcap.me
service:
  name: filesystem
  version: "1.0"
  description: 'Persistent filesystem service'
  plans: ['free']
  tags: ['filesystem', 'filesystem-1.0', 'Persistent filesystem service']
  supported_versions:
    - "1.0"
  version_aliases:
    current: "1.0"
  default_plan: free
  timeout:  10
ip_route: 127.0.0.1
index: 0
token: "0xdeadbeef"
logging:
  level: debug
mbus: nats://localhost:4222
node_timeout: 15 # higher limit for fs service
pid: /var/stackato/sys/run/filesystem_service.pid
plan: free
allow_over_provisioning: false
