---
host: 127.0.0.1
ip_route: 127.0.0.1
index: 0
logging:
  level: debug
mbus: nats://localhost:4222
local_db: sqlite3:/var/stackato/services/filesystem/filesystem_node.db # unused for now
node_id: filesystem_node_1
pid: /var/stackato/sys/run/filesystem_node.pid

max_fs_size: 500 # in MB
capacity: 20 # slots

base_dir: /var/stackato/services/filesystem/storage

supported_versions:
  - "1.0"
default_version: "1.0"
